### ISSUE TITLE
RGeo::CoordSys::Proj4.supported?` returns false with Homebrew + m1 

### ISSUE THREAD

**Issue by earnold** [rgeo/rgeo-proj4#15]
Hi there,

A helpful answer from @keithdoggett on stackoverflow pointed me to this library (thank you!). 

I'm struggling to get the install working. 

`brew install proj` works as expected.

I verified it with: 

```
$ proj  
Rel. 7.2.1, January 1st, 2021
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

I added the following to my Gemfile 
```
gem "rgeo-proj4", "~> 3.0"
```

And install worked as expected. 

However, when I try to create a factory I get the following error: 

```
> require 'rgeo'
 => false 
3.0.1 :002 > require 'rgeo/proj4'
 => false 
3.0.1 :003 > 
3.0.1 :004 > factory = RGeo::Geographic.projected_factory(projection_proj4: "EPSG:3857", projection_srid: 3857)
.../gems/rgeo-2.3.0/lib/rgeo/coord_sys.rb:45:in `check!': Coordinate system 'proj4' is not supported. (RGeo::Error::UnsupportedOperation)
```

Digging under the hood a little, I found the following: 
```
> RGeo::CoordSys::Proj4.supported?
 => false 
```

One possibility I thought of is that Homebrew isn't installing to the anticipated directory? 

```
$ which proj 
/opt/homebrew/bin/proj
```

Do you have any idea what I might need to do to get this wired up?

**Comment by keithdoggett** [comment]
Thanks for the details.

Currently the extension checks in these directories https://github.com/rgeo/rgeo-proj4/blob/ec70c88dd8a09bf20ca979764b4b00219f6581d3/ext/proj4_c_impl/extconf.rb#L15-L42

Do you happen to know where the `proj.h` header is located since that's what needs to be found for the build process to work? In the past there's also been issues with the spring gem caching non-linked versions of the gem, so running `spring stop` before `rails c` will help make sure you don't accidentally use a bad install.

**Comment by keithdoggett** [comment]
You should try `find /  -type f -name 'proj.h'` since it is probably in the `opt/homebrew/include` directory (or something like that). On Ubuntu for me it showed up in `usr/include/proj.h`.

You can also try to run this command

```ruby
require 'mkmf'

find_header('proj.h')

# or

find_header('proj.h', ['/opt/homebrew', '/opt/homebrew/include'])
```

and it will tell you if it finds the header in any of those. Just running `find_header('proj.h')` should return `false`, but adding the other paths might help us figure out where it is.

**Comment by earnold** [comment]
Hmm... I think we may be getting somewhere. 

```
$ ls /opt/homebrew/include | grep proj.h
proj.h
```
Boom! There's our `proj.h`

However....
```
$ gem uninstall rgeo-proj4                                                         
Successfully uninstalled rgeo-proj4-3.0.1
$ gem install rgeo-proj4 -- --with-proj-dir=/opt/homebrew/include                  
Fetching rgeo-proj4-3.0.1.gem
Building native extensions with: '--with-proj-dir=/opt/homebrew/include'
This could take a while...
Successfully installed rgeo-proj4-3.0.1
Parsing documentation for rgeo-proj4-3.0.1
Installing ri documentation for rgeo-proj4-3.0.1
Done installing documentation for rgeo-proj4 after 0 seconds
1 gem installed
$ irb
3.0.1 :001 > require 'rgeo'
 => true 
3.0.1 :002 > require 'rgeo/proj4'
 => true 
3.0.1 :003 > RGeo::CoordSys::Proj4.supported?
 => false 
3.0.1 :004 > 
```

So it's still not working. Anything else I can do to help debug this?

**Comment by keithdoggett** [comment]
No problem. I'll keep this open for now since I should add the homebrew install paths to the default locations the extension checks.

**Comment by zampetti** [comment]
I think maybe a new install path needs to be added for ubuntu as well...
`apt-get install libproj-dev proj-bin` installs to /usr/bin

**Comment by pcboy** [comment]
@keithdoggett Sorry to reopen, but I'm encountering the same issue on ruby:2.7.3 docker image (which is based on Debian).

```
root@7630b029eb8a:/app# gem install rgeo
Fetching rgeo-2.4.0.gem
Building native extensions. This could take a while...
Successfully installed rgeo-2.4.0
1 gem installed
root@7630b029eb8a:/app# gem install rgeo-proj4
Fetching rgeo-proj4-3.1.1.gem
Building native extensions. This could take a while...
Successfully installed rgeo-proj4-3.1.1
1 gem installed
```

So install successful.
Then:

```
irb(main):005:0> find_header('proj.h')
checking for proj.h... yes
=> true
irb(main):006:0> RGeo::CoordSys::Proj4.supported?
=> false
```

proj.h is in `/usr/include`

libproj.so is at `/usr/lib/x86_64-linux-gnu/libproj.so`

What am I missing?

**Comment by pcboy** [comment]
Found the issue.  

It's fixed by using `ruby:3.1.2` as docker base image.  
`ruby:2.7.3` ships with Debian 10.10, and when you install proj-bin you get the version 5.2.0.  

On `ruby:3.1.2`, you are on Debian 11.5, and you get proj 7.1.2. Which is then detected fine by Rgeo.  

I guess what could be improved is a warning or a stricter version check at installation of rgeo-proj4.

**Comment by keithdoggett** [comment]
@pcboy thanks for bringing that up. We do log when it's unsuccessful currently, but it goes to STDOUT which I guess is suppressed during gem installation. I might also have to change which functions are checked to ensure we've found a valid version of proj. We should probably handle it similarly to how the pg gem does and use STDERR instead (https://github.com/ged/ruby-pg/blob/499011b1be91469df8301a63817a3ff588017168/ext/extconf.rb#L116-L128).

RE: Raising if proj isn't found... I think in this case it makes sense because the gem is completely unusable if it's not able to compile proj vs RGeo core where there is still a lot of functionality without GEOS. What are your thoughts @BuonOmo?

**Comment by BuonOmo** [comment]
Yep lets raise! As PG does actually
